// Generated by `scripts/generate-sitemap.mts` from the Intlayer docs — do not edit.

import type { DocRepoMeta } from './repoMeta';

export const DOC_REPO_META: Readonly<Record<string, DocRepoMeta>> = {
  "aymericzip/intlayer-adonis-template": {
    "title": "AdonisJS i18n example: intlayer-adonis-template source code",
    "description": "AdonisJS i18n example app, browsable online. Set up Intlayer in AdonisJS: detect the locale per request with middleware, translate API responses and views…",
    "docTitle": "AdonisJS i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in AdonisJS: detect the locale per request with middleware, translate API responses and views, and keep content typed.",
    "docUrl": "https://intlayer.org/doc/environment/adonisjs",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-analog-template": {
    "title": "Analog i18n example: intlayer-analog-template source code",
    "description": "Analog i18n example app, browsable online. Set up Intlayer in Analog: typed per-component content, locale detection and switching, and localized routes for…",
    "docTitle": "Analog i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Analog: typed per-component content, locale detection and switching, and localized routes for Angular with Vite.",
    "docUrl": "https://intlayer.org/doc/environment/analog",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-angular-19-template": {
    "title": "Angular 19 i18n example: intlayer-angular-19-template source code",
    "description": "Angular 19 i18n example app, browsable online. Set up Intlayer in Angular 19 with the Angular CLI: typed content next to components, runtime locale switching…",
    "docTitle": "Angular 19 i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Angular 19 with the Angular CLI: typed content next to components, runtime locale switching and localized routing.",
    "docUrl": "https://intlayer.org/doc/environment/angular/19",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-angular-22-template": {
    "title": "Angular 22 i18n example: intlayer-angular-22-template source code",
    "description": "Angular 22 i18n example app, browsable online. Set up Intlayer in Angular 22 with Vite: typed content next to components, runtime locale switching without one…",
    "docTitle": "Angular 22 i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Angular 22 with Vite: typed content next to components, runtime locale switching without one build per language, and SEO.",
    "docUrl": "https://intlayer.org/doc/environment/angular",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-astro-template": {
    "title": "Astro i18n example: intlayer-astro-template source code",
    "description": "Astro i18n example app, browsable online. Set up Intlayer in Astro: localized routes, translated .astro pages and islands, hreflang tags and a multilingual…",
    "docTitle": "Astro i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Astro: localized routes, translated .astro pages and islands, hreflang tags and a multilingual sitemap.",
    "docUrl": "https://intlayer.org/doc/environment/astro",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-elysia-template": {
    "title": "Elysia i18n example: intlayer-elysia-template source code",
    "description": "Elysia i18n example app, browsable online. Set up Intlayer in Elysia: detect the locale per request with the plugin, translate API responses and keep content…",
    "docTitle": "Elysia i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Elysia: detect the locale per request with the plugin, translate API responses and keep content typed on Bun.",
    "docUrl": "https://intlayer.org/doc/environment/elysia",
    "updatedAt": "2026-09-29"
  },
  "aymericzip/intlayer-express-template": {
    "title": "Express i18n example: intlayer-express-template source code",
    "description": "Express i18n example app, browsable online. Set up Intlayer in Express: detect the locale per request with middleware, translate API responses and error…",
    "docTitle": "Express i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Express: detect the locale per request with middleware, translate API responses and error messages, typed end to end.",
    "docUrl": "https://intlayer.org/doc/environment/express",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-fastify-template": {
    "title": "Fastify i18n example: intlayer-fastify-template source code",
    "description": "Fastify i18n example app, browsable online. Set up Intlayer in Fastify: detect the locale per request with the plugin, translate API responses and error…",
    "docTitle": "Fastify i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Fastify: detect the locale per request with the plugin, translate API responses and error messages, typed end to end.",
    "docUrl": "https://intlayer.org/doc/environment/fastify",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-hono-template": {
    "title": "Hono i18n example: intlayer-hono-template source code",
    "description": "Hono i18n example app, browsable online. Set up Intlayer in Hono: detect the locale per request with middleware, translate API responses and run on Node, Bun…",
    "docTitle": "Hono i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Hono: detect the locale per request with middleware, translate API responses and run on Node, Bun or edge runtimes.",
    "docUrl": "https://intlayer.org/doc/environment/hono",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-htmx-template": {
    "title": "htmx i18n example: intlayer-htmx-template source code",
    "description": "htmx i18n example app, browsable online. Set up Intlayer with htmx: render translated HTML fragments on the server, detect the locale per request and switch…",
    "docTitle": "htmx i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer with htmx: render translated HTML fragments on the server, detect the locale per request and switch languages without a SPA.",
    "docUrl": "https://intlayer.org/doc/environment/htmx",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-lynx-template": {
    "title": "Lynx + React i18n example: intlayer-lynx-template source code",
    "description": "Lynx + React i18n example app, browsable online. Set up Intlayer in a Lynx and React mobile app: typed per-component content, device locale detection and a…",
    "docTitle": "Lynx + React i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in a Lynx and React mobile app: typed per-component content, device locale detection and a locale switcher.",
    "docUrl": "https://intlayer.org/doc/environment/lynx-and-react",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-next-14-template": {
    "title": "Next.js 14 i18n example: intlayer-next-14-template source code",
    "description": "Next.js 14 i18n example app, browsable online. Set up Intlayer in Next.js 14 App Router: locale routing middleware, Server and Client Components, and…",
    "docTitle": "Next.js 14 i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Next.js 14 App Router: locale routing middleware, Server and Client Components, and localized metadata and sitemap.",
    "docUrl": "https://intlayer.org/doc/environment/nextjs/14",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-next-15-template": {
    "title": "Next.js 15 i18n example: intlayer-next-15-template source code",
    "description": "Next.js 15 i18n example app, browsable online. Set up Intlayer in Next.js 15 App Router: locale routing middleware, async params, Server and Client…",
    "docTitle": "Next.js 15 i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Next.js 15 App Router: locale routing middleware, async params, Server and Client Components, localized metadata and sitemap.",
    "docUrl": "https://intlayer.org/doc/environment/nextjs/15",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-next-16-no-locale-path-template": {
    "title": "Next.js 16 i18n example: intlayer-next-16-no-locale-path-template",
    "description": "Next.js 16 i18n example app, browsable online. Set up Intlayer in Next.js 16 App Router: locale routing with the proxy, Server and Client Components…",
    "docTitle": "Next.js 16 i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Next.js 16 App Router: locale routing with the proxy, Server and Client Components, localized metadata, sitemap and static pages.",
    "docUrl": "https://intlayer.org/doc/environment/nextjs",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-next-16-template": {
    "title": "Next.js 16 i18n example: intlayer-next-16-template source code",
    "description": "Next.js 16 i18n example app, browsable online. Set up Intlayer in Next.js 16 App Router: locale routing with the proxy, Server and Client Components…",
    "docTitle": "Next.js 16 i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Next.js 16 App Router: locale routing with the proxy, Server and Client Components, localized metadata, sitemap and static pages.",
    "docUrl": "https://intlayer.org/doc/environment/nextjs",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-nuxt-4-template": {
    "title": "Nuxt i18n example: intlayer-nuxt-4-template source code",
    "description": "Nuxt i18n example app, browsable online. Set up Intlayer in Nuxt: typed per-component content, locale routing and detection, localized SEO meta and a…",
    "docTitle": "Nuxt i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Nuxt: typed per-component content, locale routing and detection, localized SEO meta and a multilingual sitemap.",
    "docUrl": "https://intlayer.org/doc/environment/nuxt-and-vue",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-react-cra-template": {
    "title": "Create React App i18n example: intlayer-react-cra-template source code",
    "description": "Create React App i18n example app, browsable online. Set up Intlayer in a Create React App project: typed content next to components, a locale switcher and…",
    "docTitle": "Create React App i18n: Complete Translation Guide",
    "docDescription": "Set up Intlayer in a Create React App project: typed content next to components, a locale switcher and translations loaded per locale.",
    "docUrl": "https://intlayer.org/doc/environment/create-react-app",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-react-native-template": {
    "title": "Expo + React Native i18n example: intlayer-react-native-template",
    "description": "Expo + React Native i18n example app, browsable online. Set up Intlayer in Expo and React Native: typed per-component content, device locale detection, a…",
    "docTitle": "Expo + React Native i18n: Complete Translation Guide",
    "docDescription": "Set up Intlayer in Expo and React Native: typed per-component content, device locale detection, a locale switcher and Metro bundling.",
    "docUrl": "https://intlayer.org/doc/environment/react-native-and-expo",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-react-router-v7-fs-routes-template": {
    "title": "React Router v7 i18n",
    "description": "React Router v7 i18n example app, browsable online. Set up Intlayer in React Router v7: localized route segments, translated loaders and components, hreflang…",
    "docTitle": "React Router v7 i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in React Router v7: localized route segments, translated loaders and components, hreflang and a multilingual sitemap.",
    "docUrl": "https://intlayer.org/doc/environment/vite-and-react/react-router-v7",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-react-router-v7-template": {
    "title": "React Router v7 i18n example: intlayer-react-router-v7-template",
    "description": "React Router v7 i18n example app, browsable online. Set up Intlayer in React Router v7: localized route segments, translated loaders and components, hreflang…",
    "docTitle": "React Router v7 i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in React Router v7: localized route segments, translated loaders and components, hreflang and a multilingual sitemap.",
    "docUrl": "https://intlayer.org/doc/environment/vite-and-react/react-router-v7",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-remix-3-template": {
    "title": "Remix 3 i18n example: intlayer-remix-3-template source code",
    "description": "Remix 3 i18n example app, browsable online. Set up Intlayer in Remix 3: locale detection in router middleware, translated route handlers and views, and…",
    "docTitle": "Remix 3 i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in Remix 3: locale detection in router middleware, translated route handlers and views, and localized URLs.",
    "docUrl": "https://intlayer.org/doc/environment/remix-3",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-solid-start-template": {
    "title": "Solid Start i18n example: intlayer-solid-start-template source code",
    "description": "Solid Start i18n example app, browsable online. Set up Intlayer in SolidStart: server-rendered locale routing, reactive translated content, hreflang and a…",
    "docTitle": "Solid Start i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in SolidStart: server-rendered locale routing, reactive translated content, hreflang and a multilingual sitemap.",
    "docUrl": "https://intlayer.org/doc/environment/solid-start",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-sveltekit-template": {
    "title": "SvelteKit i18n example: intlayer-sveltekit-template source code",
    "description": "SvelteKit i18n example app, browsable online. Set up Intlayer in SvelteKit: locale routing with hooks, translated content in load functions and components…",
    "docTitle": "SvelteKit i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in SvelteKit: locale routing with hooks, translated content in load functions and components, hreflang and sitemap.",
    "docUrl": "https://intlayer.org/doc/environment/sveltekit",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-tanstack-start-solid-template": {
    "title": "TanStack Start + Solid i18n",
    "description": "TanStack Start + Solid i18n example app, browsable online. Set up Intlayer in TanStack Start with Solid: locale route params, reactive translated content…",
    "docTitle": "TanStack Start + Solid i18n: Complete Translation Guide",
    "docDescription": "Set up Intlayer in TanStack Start with Solid: locale route params, reactive translated content, localized head metadata and hreflang.",
    "docUrl": "https://intlayer.org/doc/environment/tanstack-start/solid",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-tanstack-start-template": {
    "title": "TanStack Start i18n example: intlayer-tanstack-start-template",
    "description": "TanStack Start i18n example app, browsable online. Set up Intlayer in TanStack Start: locale route params, SSR-safe translated content, localized head…",
    "docTitle": "TanStack Start i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in TanStack Start: locale route params, SSR-safe translated content, localized head metadata, hreflang and sitemap.",
    "docUrl": "https://intlayer.org/doc/environment/tanstack-start",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-vanilla-template": {
    "title": "Vanilla JS i18n example: intlayer-vanilla-template source code",
    "description": "Vanilla JS i18n example app, browsable online. Set up Intlayer in plain JavaScript with no framework: translate a static HTML page, switch locales and keep…",
    "docTitle": "Vanilla JS i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in plain JavaScript with no framework: translate a static HTML page, switch locales and keep content typed.",
    "docUrl": "https://intlayer.org/doc/environment/vanilla",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-vite-lit-template": {
    "title": "Vite + Lit i18n example: intlayer-vite-lit-template source code",
    "description": "Vite + Lit i18n example app, browsable online. Set up Intlayer in a Vite and Lit app: translated web components with a reactive controller, a locale switcher…",
    "docTitle": "Vite + Lit i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in a Vite and Lit app: translated web components with a reactive controller, a locale switcher and typed content.",
    "docUrl": "https://intlayer.org/doc/environment/vite-and-lit",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-vite-preact-template": {
    "title": "Vite + Preact i18n example: intlayer-vite-preact-template source code",
    "description": "Vite + Preact i18n example app, browsable online. Set up Intlayer in a Vite and Preact app: typed per-component content, a locale switcher, localized routes…",
    "docTitle": "Vite + Preact i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in a Vite and Preact app: typed per-component content, a locale switcher, localized routes and small bundles.",
    "docUrl": "https://intlayer.org/doc/environment/vite-and-preact",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-vite-react-template": {
    "title": "Vite + React i18n example: intlayer-vite-react-template source code",
    "description": "Vite + React i18n example app, browsable online. Set up Intlayer in a Vite and React app: typed per-component content, a locale switcher, localized routes and…",
    "docTitle": "Vite + React i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in a Vite and React app: typed per-component content, a locale switcher, localized routes and per-locale bundles.",
    "docUrl": "https://intlayer.org/doc/environment/vite-and-react",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-vite-solid-template": {
    "title": "Vite + Solid i18n example: intlayer-vite-solid-template source code",
    "description": "Vite + Solid i18n example app, browsable online. Set up Intlayer in a Vite and Solid app: reactive translated content, a locale switcher, localized routes and…",
    "docTitle": "Vite + Solid i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in a Vite and Solid app: reactive translated content, a locale switcher, localized routes and typed dictionaries.",
    "docUrl": "https://intlayer.org/doc/environment/vite-and-solid",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-vite-svelte-template": {
    "title": "Vite + Svelte i18n example: intlayer-vite-svelte-template source code",
    "description": "Vite + Svelte i18n example app, browsable online. Set up Intlayer in a Vite and Svelte app: translated content through stores, a locale switcher, localized…",
    "docTitle": "Vite + Svelte i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in a Vite and Svelte app: translated content through stores, a locale switcher, localized routes and typed dictionaries.",
    "docUrl": "https://intlayer.org/doc/environment/vite-and-svelte",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-vite-vanilla-template": {
    "title": "Vite + Vanilla JS i18n example: intlayer-vite-vanilla-template",
    "description": "Vite + Vanilla JS i18n example app, browsable online. Set up Intlayer in a Vite app without a framework: translate the DOM, switch locales and keep typed…",
    "docTitle": "Vite + Vanilla JS i18n: Complete Translation Guide",
    "docDescription": "Set up Intlayer in a Vite app without a framework: translate the DOM, switch locales and keep typed content in .content files.",
    "docUrl": "https://intlayer.org/doc/environment/vite-and-vanilla",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/intlayer-vite-vue-template": {
    "title": "Vite + Vue i18n example: intlayer-vite-vue-template source code",
    "description": "Vite + Vue i18n example app, browsable online. Set up Intlayer in a Vite and Vue app: typed per-component content with composables, a locale switcher and…",
    "docTitle": "Vite + Vue i18n - Complete guide to translate your app",
    "docDescription": "Set up Intlayer in a Vite and Vue app: typed per-component content with composables, a locale switcher and localized routes.",
    "docUrl": "https://intlayer.org/doc/environment/vite-and-vue",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/next-i18next-template": {
    "title": "Next.js 16 i18n with next-i18next example: next-i18next-template",
    "description": "Next.js 16 i18n with next-i18next example app, browsable online. Set up next-i18next and i18next in a Next.js 16 App Router app step by step: namespaces…",
    "docTitle": "Next.js 16 i18n with next-i18next: App Router Setup Guide",
    "docDescription": "Set up next-i18next and i18next in a Next.js 16 App Router app step by step: namespaces, locale routing, server and client components, and SEO metadata.",
    "docUrl": "https://intlayer.org/blog/nextjs-internationalization-using-next-i18next",
    "updatedAt": "2026-09-27"
  },
  "aymericzip/next-intl-template": {
    "title": "Next.js 16 i18n with next-intl example: next-intl-template source code",
    "description": "Next.js 16 i18n with next-intl example app, browsable online. Set up next-intl in a Next.js 16 App Router app step by step: locale routing, per-page message…",
    "docTitle": "Next.js 16 i18n with next-intl: App Router Setup Guide",
    "docDescription": "Set up next-intl in a Next.js 16 App Router app step by step: locale routing, per-page message loading, server and client components, and SEO metadata.",
    "docUrl": "https://intlayer.org/blog/nextjs-internationalization-using-next-intl",
    "updatedAt": "2026-09-27"
  }
};
