/* eslint-disable no-console */
import { generateManifest, type Manifest } from 'material-icon-theme';
import { createRequire } from 'node:module';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const packJson = require.resolve('material-icon-theme/package.json');
const packRoot = dirname(packJson);
const iconsDir = join(packRoot, 'icons');

const root = fileURLToPath(new URL('..', import.meta.url));

/** Icon names are used verbatim in `/icons/<name>.svg` request paths. */
const SAFE_NAME = /^[a-zA-Z0-9._-]+$/;

type IconManifest = {
  file: string;
  fileExtensions: Record<string, string>;
  fileNames: Record<string, string>;
  folder: string;
  folderExpanded: string;
  folderNames: Record<string, string>;
  folderNamesExpanded: Record<string, string>;
  languageIds: Record<string, string>;
};

const collectIconNames = (m: IconManifest): Set<string> => {
  const names = new Set<string>();

  for (const value of [
    m.file,
    m.folder,
    m.folderExpanded,
    ...Object.values(m.fileExtensions),
    ...Object.values(m.fileNames),
    ...Object.values(m.folderNames),
    ...Object.values(m.folderNamesExpanded),
    ...Object.values(m.languageIds),
  ])
    if (value) names.add(value);

  return names;
};

const main = () => {
  const manifest: Manifest = generateManifest();

  const payload: IconManifest = {
    file: manifest.file!,
    fileExtensions: manifest.fileExtensions ?? {},
    fileNames: manifest.fileNames ?? {},
    folder: manifest.folder!,
    folderExpanded: manifest.folderExpanded!,
    folderNames: manifest.folderNames ?? {},
    folderNamesExpanded: manifest.folderNamesExpanded ?? {},
    languageIds: manifest.languageIds ?? {},
  };

  const outDir = join(root, 'public', 'icons');
  rmSync(outDir, { force: true, recursive: true });
  mkdirSync(outDir, { recursive: true });

  const available = new Set<string>();
  const missing = new Set<string>();

  for (const name of collectIconNames(payload)) {
    if (!SAFE_NAME.test(name)) {
      throw new Error(`Icon name is not URL-safe: ${name}`);
    }

    try {
      const svg = readFileSync(join(iconsDir, `${name}.svg`), 'utf8');
      writeFileSync(join(outDir, `${name}.svg`), svg);
      available.add(name);
    } catch {
      missing.add(name);
    }
  }

  // Some manifest entries point at icons the theme package does not ship.
  // Dropping them lets the runtime fall back to the default file/folder icon
  // instead of firing a request that can only 404.
  for (const map of [
    payload.fileExtensions,
    payload.fileNames,
    payload.folderNames,
    payload.folderNamesExpanded,
    payload.languageIds,
  ])
    for (const [key, name] of Object.entries(map))
      if (!available.has(name)) delete map[key];

  for (const name of [payload.file, payload.folder, payload.folderExpanded])
    if (!available.has(name)) {
      throw new Error(`Default icon "${name}" is missing from the theme`);
    }

  const manifestDir = join(root, 'src', 'components', '_generated');
  mkdirSync(manifestDir, { recursive: true });
  const manifestPath = join(manifestDir, 'icon-manifest.ts');
  writeFileSync(
    manifestPath,
    `/* Generated by scripts/generate-icon-theme.mts — do not edit */\n` +
      `const iconManifest = ${JSON.stringify(payload)} as const\n` +
      `export { iconManifest }\n`
  );

  console.log(
    `Wrote ${String(available.size)} SVGs to public/icons and ${manifestPath}` +
      (missing.size > 0
        ? ` (dropped ${String(missing.size)} manifest entries with no icon file)`
        : '')
  );
};

main();
