/* eslint-disable no-console */
import { generateManifest, type Manifest } from 'material-icon-theme';
import { createRequire } from 'node:module';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const packJson = require.resolve('material-icon-theme/package.json');
const packRoot = dirname(packJson);
const iconsDir = join(packRoot, 'icons');

const collectIconNames = (m: Manifest, into: Set<string>) => {
  for (const v of [
    m.file,
    m.folder,
    m.folderExpanded,
    m.rootFolder,
    m.rootFolderExpanded,
    ...Object.values(m.folderNames ?? {}),
    ...Object.values(m.folderNamesExpanded ?? {}),
    ...Object.values(m.rootFolderNames ?? {}),
    ...Object.values(m.rootFolderNamesExpanded ?? {}),
    ...Object.values(m.fileExtensions ?? {}),
    ...Object.values(m.fileNames ?? {}),
    ...Object.values(m.languageIds ?? {}),
  ])
    if (v) into.add(v);

  for (const def of Object.values(m.iconDefinitions ?? {}))
    if (def?.iconPath) {
      const base = def.iconPath.replace(/\.svg$/i, '');
      into.add(base);
    }
  if (m.light) collectIconNames(m.light, into);
  if (m.highContrast) collectIconNames(m.highContrast, into);
};

const main = () => {
  const manifest = generateManifest();
  const usedIcons = new Set<string>();
  collectIconNames(manifest, usedIcons);

  const svgMap: Record<string, string> = {};
  for (const name of usedIcons) {
    try {
      svgMap[name] = readFileSync(join(iconsDir, `${name}.svg`), 'utf8');
    } catch {
      /* icon file not found */
    }
  }

  const outDir = join(fileURLToPath(new URL('..', import.meta.url)), 'src', '_generated');
  mkdirSync(outDir, { recursive: true });
  const payload = {
    manifest: {
      file: manifest.file,
      fileExtensions: manifest.fileExtensions,
      fileNames: manifest.fileNames,
      folder: manifest.folder,
      folderExpanded: manifest.folderExpanded,
      folderNames: manifest.folderNames,
      folderNamesExpanded: manifest.folderNamesExpanded,
      languageIds: manifest.languageIds,
    },
    svgs: svgMap,
  };
  const outPath = join(outDir, 'icons.ts');
  writeFileSync(
    outPath,
    `/* Generated by scripts/generate-icon-theme.mts — do not edit */\n` +
      `const icons = ${JSON.stringify(payload)} as const\n` +
      `export { icons }\n`
  );
  const folderCount = Object.keys(manifest.folderNames ?? {}).length;
  console.log(
    `Wrote ${outPath}: ${String(Object.keys(svgMap).length)} SVGs, ` +
      `${String(folderCount)} folder name mappings`
  );
};

main();
